# Generated by Django 5.2 on 2025-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_category_tag_user_delete_userinfo_article_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="articles", to="blog.category"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="articles", to="blog.tag"
            ),
        ),
    ]
