# Generated by Django 5.2 on 2025-04-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_categories_alter_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="blog.category"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="blog.tag"
            ),
        ),
    ]
