# Generated by Django 5.2 on 2025-04-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_article_categories_alter_article_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelTable(
            name="user",
            table="blog_user",
        ),
    ]
